# Generated by Django 5.2.17 on 2026-09-29 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('meat', 'Meat'), ('seafood', 'Seafood'), ('dairy', 'Dairy & Eggs'), ('grains', 'Grains & Legumes'), ('spices', 'Spices & Herbs'), ('pantry', 'Pantry'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('is_purchased', models.BooleanField(default=False)),
                ('from_plan', models.BooleanField(default=False, help_text="Created by 'Generate from meal plan'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_purchased', 'name'],
                'indexes': [models.Index(fields=['user', 'is_purchased'], name='shopping_sh_user_id_0b79ae_idx')],
            },
        ),
    ]
